version: '3.8'

services:
  plantas-service:
    build: ./plantas-service
    container_name: plantas-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - plantas-network
    restart: unless-stopped

  cuidados-service:
    build: ./cuidados-service
    container_name: cuidados-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1
    networks:
      - plantas-network
    restart: unless-stopped

networks:
  plantas-network:
    driver: bridge

